import type { Component } from 'vue';
import {
  Atom,
  BookOpen,
  Bot,
  Brain,
  Braces,
  BrickWall,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  ClipboardList,
  CodeXml,
  Columns3,
  Command,
  Copy,
  Download,
  ExternalLink,
  FileDown,
  FileText,
  GitCompareArrows,
  Globe2,
  History,
  Image,
  Keyboard,
  Languages,
  LayoutTemplate,
  Library,
  Lightbulb,
  List,
  ListChecks,
  MessageCircle,
  Mic,
  Moon,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  PenLine,
  Pencil,
  Play,
  Plus,
  Puzzle,
  RotateCcw,
  Search,
  Settings2,
  Share2,
  Sparkles,
  SquareCheckBig,
  Star,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  Volume2,
  VolumeX,
  X,
  Zap,
} from '@lucide/vue';

export const assistantIcons = {
  atom: Atom,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  braces: Braces,
  'brick-wall': BrickWall,
  'briefcase-business': BriefcaseBusiness,
  'chart-no-axes-combined': ChartNoAxesCombined,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  circle: Circle,
  'clipboard-list': ClipboardList,
  'code-xml': CodeXml,
  'columns-3': Columns3,
  command: Command,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  'file-down': FileDown,
  'file-text': FileText,
  'git-compare-arrows': GitCompareArrows,
  'globe-2': Globe2,
  history: History,
  image: Image,
  keyboard: Keyboard,
  languages: Languages,
  'layout-template': LayoutTemplate,
  library: Library,
  lightbulb: Lightbulb,
  list: List,
  'list-checks': ListChecks,
  'message-circle': MessageCircle,
  mic: Mic,
  moon: Moon,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  paperclip: Paperclip,
  'pen-line': PenLine,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  'rotate-ccw': RotateCcw,
  search: Search,
  'settings-2': Settings2,
  'share-2': Share2,
  sparkles: Sparkles,
  'square-check-big': SquareCheckBig,
  star: Star,
  sun: Sun,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  user: User,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  x: X,
  zap: Zap,
} satisfies Record<string, Component>;

export type AssistantIconName = keyof typeof assistantIcons;

export function resolveAssistantIcon(name: string): Component | undefined {
  if (!Object.prototype.hasOwnProperty.call(assistantIcons, name)) return undefined;
  return assistantIcons[name as AssistantIconName];
}
