apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  access-token: {{ .Values.secrets.accessToken | b64enc | quote }}
  admin-token: {{ .Values.secrets.adminToken | b64enc | quote }}
  runtime-config-secret-key: {{ .Values.secrets.runtimeConfigSecretKey | b64enc | quote }}
