/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description LLM response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Compatibility SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Typed SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available model list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime configuration summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeModelConfigResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/runtime/model-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin runtime model configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeModelConfigResult"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RuntimeModelConfigPayload"];
                };
            };
            responses: {
                /** @description Updated runtime model configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeModelConfigResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prompt template registry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PromptTemplateEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/url-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    url: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fetched page preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UrlPreviewResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatRequest: {
            /** @enum {string} */
            action?: "translate" | "summarize" | "chat";
            text: string;
            targetLang?: string;
            history?: components["schemas"]["MessageItem"][];
            systemPrompt?: string;
            model?: string;
            imageData?: string;
            imageDataList?: string[];
            pageContext?: string;
            sessionId?: string;
        };
        MessageItem: {
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
        };
        ChatResponse: {
            success: boolean;
            result?: string;
            error?: string;
            errorCode?: string;
            meta?: components["schemas"]["RuntimeMeta"];
        };
        RuntimeMeta: {
            requestedModel?: string;
            effectiveModel?: string;
            provider?: string;
            fallback?: boolean;
            visionInputCount?: number;
            visionRoute?: string;
        };
        ModelsListResponse: {
            success: boolean;
            models?: string[];
            defaultModel?: string;
            modelDetails?: components["schemas"]["ModelDetail"][];
            error?: string;
        };
        ModelDetail: {
            id: string;
            capabilities?: string[];
            source?: string;
            updatedAt?: string;
        };
        RuntimeModelConfigResult: {
            success: boolean;
            provider?: string;
            baseUrl?: string;
            model?: string;
            allowedModels?: string[];
            apiKeyConfigured?: boolean;
            minimaxVlmBaseUrl?: string;
            error?: string;
        };
        RuntimeModelConfigPayload: {
            provider?: string;
            baseUrl?: string;
            apiKey?: string;
            model?: string;
            allowedModelsText?: string;
            minimaxVlmBaseUrl?: string;
        };
        PromptTemplateEntry: {
            name: string;
            template: string;
            hasFewShot?: boolean;
        };
        AdminOverview: {
            usage: {
                [key: string]: unknown;
            };
            tokenUsage: {
                [key: string]: unknown;
            };
            registeredTools: number;
            promptTemplates: number;
            activeABTests: number;
        };
        AdminPromptEntry: {
            name: string;
            template: string;
        };
        AdminToolEntry: {
            name: string;
            description: string;
        };
        AdminRagStats: {
            namespace: string;
            documentCount: number;
        };
        AdminRagIngestResult: {
            success: boolean;
            namespace: string;
            chunks: number;
        };
        AdminAbTestConfig: {
            modelA?: string;
            modelB?: string;
            percentA?: number;
        } & {
            [key: string]: unknown;
        };
        AdminFallbackChain: {
            chain: string[];
        };
        AdminPluginsResult: {
            plugins: {
                [key: string]: unknown;
            };
            enabled: boolean;
        };
        AdminSystemInfo: {
            javaVersion?: string;
            osName?: string;
            availableProcessors?: number;
            maxMemoryMb?: number;
            freeMemoryMb?: number;
            totalMemoryMb?: number;
            registeredTools?: number;
            promptTemplates?: number;
            fallbackChain?: string[];
            loadedPlugins?: number;
        };
        UrlPreviewResponse: {
            success: boolean;
            imageUrl?: string;
            title?: string;
            summary?: string;
            imageUrls?: string[];
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
